# Generated by Django 5.2.3 on 2026-04-25 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Cyber Security', max_length=200)),
                ('head_of_department', models.CharField(max_length=200)),
                ('about', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Faculty of Computing', max_length=200)),
                ('dean', models.CharField(help_text='Name of the Dean of the Faculty', max_length=200)),
                ('about', models.TextField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Faculties',
            },
        ),
        migrations.CreateModel(
            name='AdmissionRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jamb_cutoff_mark', models.IntegerField(default=150)),
                ('jamb_subject_combination', models.CharField(default='Use of English and three other relevant subjects.', help_text='e.g., Use of English, Math, Physics, and Chemistry', max_length=255)),
                ('compulsory_olevel_subjects', models.TextField(help_text='e.g., 5 Credits including English and Math.')),
                ('accepts_two_sittings', models.BooleanField(default=True, help_text='Check if a student can combine WAEC and NECO.')),
                ('requires_math_credit', models.BooleanField(default=True, help_text='Does this specific course absolutely require a Math credit?')),
                ('post_utme_screening', models.BooleanField(default=False, help_text="True if there is an exam. False if it's just physical document screening.")),
                ('requires_first_choice', models.BooleanField(default=True, help_text='Must BIU be their 1st choice on the JAMB portal?')),
                ('accepts_direct_entry', models.BooleanField(default=True)),
                ('de_minimum_qualification', models.CharField(default='Minimum of Lower Credit in OND, or valid JUPEB/IJMB.', help_text='Specify if they need Upper Credit, or if JUPEB is accepted.', max_length=200)),
                ('accepts_transfers', models.BooleanField(default=True, help_text='Can a 200L student from another university transfer here?')),
                ('minimum_transfer_cgpa', models.CharField(blank=True, help_text='e.g., Minimum CGPA of 2.5 on a 5.0 scale.', max_length=100, null=True)),
                ('total_school_fees', models.CharField(help_text='e.g., ₦850,000 per session', max_length=100)),
                ('acceptance_fee', models.CharField(default='₦50,000 (Non-refundable)', max_length=100)),
                ('hostel_fees_included', models.BooleanField(default=False, help_text='Are hostel accommodations part of the total_school_fees?')),
                ('allows_installment_payments', models.BooleanField(default=True, help_text='Can parents pay per semester?')),
                ('scholarships_available', models.BooleanField(default=True, help_text='Are there sibling discounts or bishopric scholarships?')),
                ('admission_deadline', models.CharField(blank=True, help_text='e.g., October 31st, 2026', max_length=100, null=True)),
                ('nuc_accreditation_status', models.CharField(default='Fully Accredited', help_text='e.g., Fully Accredited, Interim, or Pending.', max_length=100)),
                ('duration_years', models.IntegerField(default=4, help_text='How many years does this course take? (e.g., 4, 5, 6)')),
                ('is_currently_admitting', models.BooleanField(default=True, help_text='Uncheck if the department has reached its quota for the year.')),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission_info', to='myproject.department')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='myproject.faculty'),
        ),
        migrations.CreateModel(
            name='LevelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(100, '100 Level'), (200, '200 Level'), (300, '300 Level'), (400, '400 Level'), (500, '500 Level')])),
                ('course_advisor', models.CharField(help_text='Name of the lecturer advising this level', max_length=200)),
                ('class_rep_name', models.CharField(blank=True, max_length=200, null=True)),
                ('special_status', models.CharField(default='In Session', help_text='e.g., In Session, On SIWES, Graduated', max_length=200)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='myproject.department')),
            ],
            options={
                'unique_together': {('department', 'level')},
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(help_text='e.g., CYB303', max_length=10)),
                ('title', models.CharField(help_text='e.g., Information Security Risk Management', max_length=200)),
                ('credit_units', models.IntegerField(default=3)),
                ('is_compulsory', models.BooleanField(default=True)),
                ('level_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='myproject.levelinfo')),
            ],
        ),
    ]
