# Generated by Django 5.2.3 on 2026-04-25 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='levelinfo',
            old_name='class_rep_name',
            new_name='course_rep_name',
        ),
    ]
