# Generated by Django 5.2.3 on 2026-04-25 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0002_rename_class_rep_name_levelinfo_course_rep_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('1st', 'First Semester'), ('2nd', 'Second Semester')], default='1st', max_length=3),
        ),
    ]
